import './globals.css';
import { Inter } from '@next/font/google'
import Head from 'next/head';

const inter = Inter({
  variable: '--inter-font'
})
export default function RootLayout({
  children,
  className,
}: {
  children: React.ReactNode;
  className?: string;
}) {
  return (
    <html lang="en" className={inter.className}>
      <Head>
        <title>Ahmadsan</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <body className={className}>{children}</body>
    </html>
  );
}
