import './globals.css';
import Head from 'next/head';
export default function RootLayout({
  children,
  className,
}: {
  children: React.ReactNode;
  className?: string;
}) {
  return (
    <html lang="en">
      <Head>
        <title>Ahmadsan</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <body className={className}>{children}</body>
    </html>
  );
}
